export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';

export const Loading = {
  DOWNLOAD_START: 'DOWNLOAD_START',
  DOWNLOAD_END: 'DOWNLOAD_END',
  LOADING_START: 'LOADING_START',
  LOADING: 'LOADING',
  LOADING_ALL_PACKAGE: 'LOADING_ALL_PACKAGE',
};
export const VisibilityFilters = {
  CHEAPEST: 'CHEAPEST',
  FASTEST: 'FASTEST',
  OPTIMAL: 'OPTIMAL',
};
export const VisibilityChange = {
  ALL: 'ALL',
  NON_STOP: 'NON_STOP',
  ONE_TRANSFER: 'ONE_TRANSFER',
  TWO_TRANSFER: 'TWO_TRANSFER',
  THREE_TRANSFERS: 'THREE_TRANSFERS',
};
